### PR TITLE
ttRunPackage does not wait for configuration to be loaded (#148)

### LINKED ISSUE #148: ttRunPackage does not wait for configuration to be loaded
### Describe the bug

Test execution via Jenkins is failing due to unavailable tools. The same test can be executed locally.

In a Jenkins job a test execution is started with a block like
```
                ttStartTool toolName: 'ecu.test', workspaceDir: 'ECU-TEST_Workspace'
                ttRunPackage testCasePath: '***.pkg', testConfig: [tbcPath: '***.tbc', tcfPath: '***.tcf']
                ttStopTool toolName: 'ecu.test'
```

The test exection fails as the tools configured in the test bench configuration are not available.

Partial content of `ecu.test_out.log`:
```
2024-06-03 14:20:23.476 2356 Thread-9 DEBUG:
                        REST-API now available at 127.0.0.1:5050
2024-06-03 14:20:23.620 2356 MainThread DEBUG:
                        SWK: Catalog switching UI: Global- (False)
2024-06-03 14:20:27.286 2356 WSGI_0 DEBUG:
                        Add configuration change order.
2024-06-03 14:20:27.289 2356 WSGI_0 DEBUG:
                        Add execution ***.pkg
2024-06-03 14:20:27.296 2356 Thread-11 INFO:
                        REST API: Start Package ***.pkg
2024-06-03 14:20:27.296 2356 Thread-11 DEBUG:
                        Start execution of Package ***.pkg
2024-06-03 14:20:27.425 2356 Thread-11 DEBUG:
                        Wait for Package ***.pkg to finish
2024-06-03 14:20:27.825 2356 ManagedWorker-1*PE.Run() INFO:
                        Start package '***.pkg' with test case execution with sequential analysis job execution
2024-06-03 14:20:28.051 2356 ManagedWorker-1*PE.Run() INFO:
                        Test case "***" started
2024-06-03 14:20:28.109 2356 ManagedWorker-1*PE.Run() DEBUG:
                        TestEngine: Start ports...
2024-06-03 14:20:28.109 2356 ManagedWorker-1*PE.Run() WARNING:
                        Port missing in the test bench configuration: DIAG-CAN-FD01
2024-06-03 14:20:28.111 2356 ManagedWorker-1*PE.Run() WARNING:
                        Port missing in the test bench configuration: DIAG-DOIP-SOCKET01
2024-06-03 14:20:28.603 2356 ManagedWorker-1*PE.Run() INFO:
                        System time mode activated
2024-06-03 14:20:28.624 2356 ManagedWorker-1*PE.Run() ERROR:
                        Test step .1(Parse_Input_Check).1(Parse_Input).1(Calculation): "An error occurred when calling "parse_parameters(***)": Runtime error in function variable, line 75: TypeError, object of type 'NoneType' has no len()."
                        Package "ECU-TEST_Workspace\Packages\Parse_Input.pkg"#1
2024-06-03 14:20:28.791 2356 ManagedWorker-1*PE.Run() DEBUG_EXC_PRINT:
                        tts.testExecution.engine.TestEngine.ExecuteTestStep: UserCodeException: An error occurred when calling "parse_parameters(***)": Runtime error in function variable, line 75: TypeError, object of type 'NoneType' has no len().
                        Package "ECU-TEST_Workspace\Packages\Parse_Input.pkg"#1
2024-06-03 14:20:28.892 2356 ManagedWorker-1*PE.Run() WARNING:
                        Test case "***" aborted
2024-06-03 14:20:28.897 2356 ManagedWorker-1*PE.Run() DEBUG:
                        TestEngine: Stop ports...
2024-06-03 14:20:28.899 2356 ManagedWorker-1*PE.Run() INFO:
                        Test case "***" completed
2024-06-03 14:20:29.269 2356 Thread-11 DEBUG:
                        Extract results for Package ***.pkg
2024-06-03 14:20:29.303 2356 Thread-11 INFO:
                        REST API: Package ***.pkg successfully completed
2024-06-03 14:20:29.303 2356 Thread-11 INFO:
                        REST-API: Start the configuration
2024-06-03 14:20:29.304 2356 Thread-11 DEBUG:
                        ActiveConfigManager: Load TBC: ECU-TEST_Workspace\Configurations\***.tbc

```

The exception at timestamp `2024-06-03 14:20:28.624` is caused by `api.ObjectApi.ConfigurationApi.OpenTestBenchConfiguration(api.CurrentTestbenchConfiguration.Filename).GetTool('***')` being `None` despite this tool being configured in the test bench configuration.

The log seems to indicate that the REST API requests to load the configuration (`2024-06-03 14:20:27.286`) and start the test execution (`2024-06-03 14:20:27.289`) are sent without actually waiting for the configuration to load. Loading/starting of the configuration (`2024-06-03 14:20:29.303`) only starts after the test execution (`2024-06-03 14:20:27.296`-`2024-06-03 14:20:29.303`).

### Steps to reproduce

-

### Expected behavior

Test execution via Jenkins is starting the test bench configuration prior to starting the test execution.

### Versions

- Jenkins: 2.452.1
- Plugin: 3.4
- ecu.test: 2024.1.1
- test.guide:

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TT-S3-D1**
Fixes #148

### CODE REVIEW

File: src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunPackageStepIT.groovy [hunk 1]
```diff
@@ -210,22 +209,52 @@ class RunPackageStepIT extends IntegrationTestBase {
...
+            WorkflowJob job = jenkins.createProject(WorkflowJob.class, 'pipeline')
+            job.setDefinition(new CpsFlowDefinition("node { ttRunPackage testCasePath: 'test.pkg', testConfig: [tbcPath: 'test.tbc'] }", true))
+        when:
+            WorkflowRun run = jenkins.assertBuildStatus(Result.FAILURE, job.scheduleBuild2(0).get())
+        then:
+            jenkins.assertLogContains("Executing package 'test.pkg'", run)
+            jenkins.assertLogNotContains('ecu.test is busy', run)
+            jenkins.assertLogContains('unauthorized', run)
+        and:
+            // cannot use interactive based testing since the method call was not fully ended
```
Comment (MxEh-TT) [inline src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunPackageStepIT.groovy:239]: sounds a bit strange
"interactive-based testing cannot be used because the method call does not fully end."
or
"interactive-based testing cannot be used because the method call does not fully complete."

File: src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunProjectStepIT.groovy [hunk 2]
```diff
@@ -153,6 +153,38 @@ class RunProjectStepIT extends IntegrationTestBase {
...
+            WorkflowJob job = jenkins.createProject(WorkflowJob.class, 'pipeline')
+            job.setDefinition(new CpsFlowDefinition("node { ttRunProject testCasePath: 'test.prj', testConfig: [tbcPath: 'test.tbc'] }", true))
+        when:
+            WorkflowRun run = jenkins.assertBuildStatus(Result.FAILURE, job.scheduleBuild2(0).get())
+        then:
+            jenkins.assertLogContains("Executing project 'test.prj'", run)
+            jenkins.assertLogNotContains('ecu.test is busy', run)
+            jenkins.assertLogContains('unauthorized', run)
+        and:
+            // cannot use interactive based testing since the method call was not fully ended
```
Comment (MxEh-TT) [inline src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunProjectStepIT.groovy:184]: see above

**Review by MxEh-TT — APPROVED** [review]
