### PR TITLE
i262: redirect stdout and stderr of started tools to a file to empty the buffer

### LINKED ISSUE #262: Failed to start ecu.test_runner.exe
### Describe the bug

When triggering ecu.test_runner.exe through Jenkins, the process does not start successfully.
However, when the same executable is launched manually on the local machine, it opens and executes the tests without any issues.

### Steps to reproduce

* steps for the reproduction in https://support.tracetronic.com/browse/TT-24562

### Expected behavior

The ecu.test runner for windows can be automated as expected.

### Versions

- Jenkins: *
- Plugin: 3.11
- ecu.test: 2026.1
- test.guide: -

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tt-tiwe**
resolves #262

### CODE REVIEW

File: src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy [hunk 1]
```diff
@@ -276,6 +290,25 @@ class StartToolStep extends Step {
                             "within the timeout of ${timeout} seconds.")
         }
 
+        /**
+         * Ensures that the target directory exists and can be used for log output.
+         */
+        private void ensureDirectoryExists(String directoryPath) {
```
Comment (MartinGroscheTT) [inline src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy]: The `checkWorkspace()` method already verifies the existence of the required ecu.test directories. Consequently, it would be advisable to relocate this functionality to the `ExecutionCallable `class and, where appropriate, merge the checks into a single cohesive routine.

File: src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy [hunk 2]
```diff
@@ -290,6 +323,81 @@ class StartToolStep extends Step {
...
 
+    /**
+     * Creates a File with a sanitized filename based on the toolName.
+     * @param directory The directory to create the file in
+     * @param rawToolName The toolName provided by the user
+     * @param suffix The suffix to add to the sanitized toolName
+     * @return {@link File} with sanitized filename
+     */
+    static File createLogFile(String directory, String rawToolName, String suffix) {
+        String safeToolName = sanitizeForFilename(rawToolName, 'tool')
```
Comment (MartinGroscheTT) [inline src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy]: The fallback handling for toolname can be incorporated directly into the method itself, as there are no other references to it elsewhere.

File: src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy [hunk 3]
```diff
@@ -290,6 +323,81 @@ class StartToolStep extends Step {
...
+        // Neutralize repeated dots so traversal-like inputs cannot survive as meaningful segments.
+        name = name.replaceAll(/\.\.+/, '_')
+        // Trim trailing dot/space because Windows does not allow them at the end of a file name.
+        name = name.replaceAll(/[. ]+$/, '')
+        // Collapse duplicate underscores introduced by previous replacements.
+        name = name.replaceAll(/_+/, '_')
+        name = StringUtils.trimToEmpty(name)
+
+        // If no letter (Unicode characters are allowed) or digit is left, use fallback
+        if (!containsLetterOrDigit(name)) {
```
Comment (MartinGroscheTT) [inline src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy:377]: If the fallback logic is relocated within this method, it can be returned directly.

**Review by MartinGroscheTT — CHANGES_REQUESTED** [review]

**Review by MartinGroscheTT — COMMENTED** [review]
- is teh support for ecu.test-runner.exe tested?
- i am missing a test that checks if the log files were really created, may use the internal Jenkins environment to archive those two files as well
- since we redirect the out/error they disappear from the Jenkins log

**Comment by tt-tiwe** [comment]
I added a test, that checks the creation of the log files.
The stdout and stderr did not end up in the jenkins log before either, so they did not disappear but rather they were never there in the first place.

**Review by MartinGroscheTT — APPROVED** [review]
