### PR TITLE
Fix license popup on windows ecu.test startup

### LINKED ISSUE #215: When starting ecu.test on windows a license popup is displayed
### Description

When starting ecu.test with this plugin on a windows machine, a license popup containing license information is displayed. ecu.test is blocked until popup gets confirmed.

### Steps to reproduce

- run `ttStartTool` on a windows node

### Expected behavior

- there is no popup windows
- ecu.test starts without manual interaction

### Versions

Plugin: 3.7
ecu.test: 2024.4

### PR DESCRIPTION
**Pull request by ErikRehmTT**
Fixes #215

### CODE REVIEW

File: src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy [hunk 1]
```diff
@@ -283,34 +242,42 @@ class StartToolStep extends Step {
...
+                    exitCode = process.exitValue()
+                }  catch (IllegalThreadStateException ignore){
+                    throw new AbortException(
+                            "Timeout of ${this.timeout} seconds exceeded for connecting to ${toolName}! " +
+                                    "Please ensure the tool is correctly configured and consider restarting it.")
                 }
             }
+            if (exitCode == 0) {
+                return
+            }
```
Comment (ErikRehmTT) [inline src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy:258]: could/should be the else branch of the if before

File: src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy [hunk 2]
```diff
@@ -283,34 +242,42 @@ class StartToolStep extends Step {
...
-                    Thread.sleep(1000)
+            boolean  isConnected = checkToolConnection()
+            int exitCode = 0
+            if (!isConnected) {
+                try  {
+                    exitCode = process.exitValue()
+                }  catch (IllegalThreadStateException ignore){
+                    throw new AbortException(
+                            "Timeout of ${this.timeout} seconds exceeded for connecting to ${toolName}! " +
+                                    "Please ensure the tool is correctly configured and consider restarting it.")
```
Comment (ErikRehmTT) [inline src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy:253]: We might want to stop/kill the process before throwing the exception.

File: src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy [hunk 3]
```diff
@@ -283,34 +242,42 @@ class StartToolStep extends Step {
...
-                        "Timeout of ${this.timeout} seconds exceeded for starting ${toolName}! " +
-                        "Please ensure that the tool is correctly configured and accessible.")
+            if (exitCode == 99) {
+                throw new AbortException("No valid license found for ${toolName}! " +
+                        "Please ensure the license is not expired or corrupted.")
             }
+
+            throw new AbortException(
+                    "Timeout of ${this.timeout} seconds exceeded for connecting to ${toolName}! " +
+                            "Please ensure the tool is correctly configured and consider restarting it.")
```
Comment (ErikRehmTT) [inline src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy:267]: Having the same Exception for two different behaviors is odd. Here we might want to inform the user (or better us as support) that ecu.test did not start correctly and exited during within the timeout. Adding the exit code to the message.

File: src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStepIT.groovy [hunk 4]
```diff
@@ -186,139 +188,129 @@ class StartToolStepIT extends IntegrationTestBase {
...
+            RestApiClientFactory.getRestApiClient(_, _, _) >> restApiClientMock
+        and:
+            Process processMock = GroovyMock(Process)
+            ProcessBuilder processBuilderMock = GroovySpy(ProcessBuilder, global: true)
+            new ProcessBuilder(_) >> processBuilderMock
+            processBuilderMock.command(_) >> processBuilderMock
+            processBuilderMock.start() >> processMock
         when:
-            WorkflowRun run = jenkins.assertBuildStatus(Result.FAILURE, job.scheduleBuild2(0).get())
+            WorkflowRun run = jenkins.assertBuildStatus(Result.SUCCESS, job.scheduleBuild2(0).get())
```
Comment (ErikRehmTT) [inline src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStepIT.groovy:212]: Build jobs failed here

**Comment by ErikRehmTT** [comment]
As the big testing improvement branch was merged this morning a rebase is needed

File: src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy [hunk 5]
```diff
@@ -283,34 +243,41 @@ class StartToolStep extends Step {
...
-                        "Timeout of ${this.timeout} seconds exceeded for starting ${toolName}! " +
-                        "Please ensure that the tool is correctly configured and accessible.")
+            if (exitCode == 99) {
+                throw new AbortException("No valid license found for ${toolName}! " +
+                        "Please ensure the license is not expired or corrupted.")
             }
+
+            throw new AbortException(
+                    "${toolName} did not start correctly and stopped with exit code ${exitCode} and " +
+                            "was terminated within the timeout of ${timeout} seconds.")
```
Comment (ErikRehmTT) [inline src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy:268]: `and was terminated` is duplicate of ``stopped` and can be removed from the sentence

**Review by ErikRehmTT — COMMENTED** [review]
A container test failed, which might need to get fixed

**Review by MxEh-TT — APPROVED** [review]
